/// <reference types="react" />
/// <reference types="react" />
/// <reference types="trusted-types" />
/// <reference types="react-draggable" />
/** @jsx jsx */
import { type PopperProps } from 'jimu-ui';
import { React, ReactRedux, type BrowserSizeMode, type IMThemeVariables, jsx } from 'jimu-core';
interface StateToPopperProps {
    pageId: string;
    sizemode: BrowserSizeMode;
    dispatch?: any;
}
declare class PageAwarePopper extends React.PureComponent<PopperProps & StateToPopperProps & {
    theme?: IMThemeVariables;
}> {
    componentDidUpdate(prevProps: PopperProps & StateToPopperProps): void;
    getStyle(): import("jimu-core").SerializedStyles;
    render(): jsx.JSX.Element;
}
declare const _default: ReactRedux.ConnectedComponent<typeof PageAwarePopper, {
    color?: string;
    content?: string;
    position?: import("react-draggable").ControlPosition;
    translate?: "yes" | "no";
    zIndex?: number;
    offset?: number[];
    ref?: React.LegacyRef<PageAwarePopper>;
    theme?: IMThemeVariables;
    id?: string;
    size?: import("jimu-ui").Size;
    children: React.ReactNode;
    slot?: string;
    style?: React.CSSProperties;
    dir?: string;
    onClick?: React.MouseEventHandler<HTMLDivElement>;
    hidden?: boolean;
    open: boolean;
    about?: string;
    is?: string;
    onChange?: React.FormEventHandler<HTMLDivElement>;
    defaultChecked?: boolean;
    defaultValue?: string | number | readonly string[];
    suppressContentEditableWarning?: boolean;
    suppressHydrationWarning?: boolean;
    accessKey?: string;
    autoFocus?: boolean;
    className?: string;
    contentEditable?: "inherit" | (boolean | "false" | "true") | "plaintext-only";
    contextMenu?: string;
    draggable?: boolean | "false" | "true";
    lang?: string;
    nonce?: string;
    spellCheck?: boolean | "false" | "true";
    tabIndex?: number;
    radioGroup?: string;
    role?: React.AriaRole;
    datatype?: string;
    inlist?: any;
    prefix?: string;
    property?: string;
    rel?: string;
    resource?: string;
    rev?: string;
    typeof?: string;
    vocab?: string;
    autoCapitalize?: string;
    autoCorrect?: string;
    autoSave?: string;
    itemProp?: string;
    itemScope?: boolean;
    itemType?: string;
    itemID?: string;
    itemRef?: string;
    results?: number;
    security?: string;
    unselectable?: "off" | "on";
    inputMode?: "search" | "none" | "text" | "decimal" | "url" | "email" | "tel" | "numeric";
    "aria-activedescendant"?: string;
    "aria-atomic"?: boolean | "false" | "true";
    "aria-autocomplete"?: "none" | "both" | "inline" | "list";
    "aria-braillelabel"?: string;
    "aria-brailleroledescription"?: string;
    "aria-busy"?: boolean | "false" | "true";
    "aria-checked"?: boolean | "mixed" | "false" | "true";
    "aria-colcount"?: number;
    "aria-colindex"?: number;
    "aria-colindextext"?: string;
    "aria-colspan"?: number;
    "aria-controls"?: string;
    "aria-current"?: boolean | "page" | "time" | "false" | "true" | "step" | "location" | "date";
    "aria-describedby"?: string;
    "aria-description"?: string;
    "aria-details"?: string;
    "aria-disabled"?: boolean | "false" | "true";
    "aria-dropeffect"?: "link" | "none" | "copy" | "move" | "execute" | "popup";
    "aria-errormessage"?: string;
    "aria-expanded"?: boolean | "false" | "true";
    "aria-flowto"?: string;
    "aria-grabbed"?: boolean | "false" | "true";
    "aria-haspopup"?: boolean | "grid" | "dialog" | "menu" | "listbox" | "false" | "true" | "tree";
    "aria-hidden"?: boolean | "false" | "true";
    "aria-invalid"?: boolean | "false" | "true" | "grammar" | "spelling";
    "aria-keyshortcuts"?: string;
    "aria-label"?: string;
    "aria-labelledby"?: string;
    "aria-level"?: number;
    "aria-live"?: "off" | "assertive" | "polite";
    "aria-modal"?: boolean | "false" | "true";
    "aria-multiline"?: boolean | "false" | "true";
    "aria-multiselectable"?: boolean | "false" | "true";
    "aria-orientation"?: "horizontal" | "vertical";
    "aria-owns"?: string;
    "aria-placeholder"?: string;
    "aria-posinset"?: number;
    "aria-pressed"?: boolean | "mixed" | "false" | "true";
    "aria-readonly"?: boolean | "false" | "true";
    "aria-relevant"?: "all" | "text" | "additions" | "additions removals" | "additions text" | "removals" | "removals additions" | "removals text" | "text additions" | "text removals";
    "aria-required"?: boolean | "false" | "true";
    "aria-roledescription"?: string;
    "aria-rowcount"?: number;
    "aria-rowindex"?: number;
    "aria-rowindextext"?: string;
    "aria-rowspan"?: number;
    "aria-selected"?: boolean | "false" | "true";
    "aria-setsize"?: number;
    "aria-sort"?: "none" | "ascending" | "descending" | "other";
    "aria-valuemax"?: number;
    "aria-valuemin"?: number;
    "aria-valuenow"?: number;
    "aria-valuetext"?: string;
    dangerouslySetInnerHTML?: {
        __html: string | TrustedHTML;
    };
    onCopy?: React.ClipboardEventHandler<HTMLDivElement>;
    onCopyCapture?: React.ClipboardEventHandler<HTMLDivElement>;
    onCut?: React.ClipboardEventHandler<HTMLDivElement>;
    onCutCapture?: React.ClipboardEventHandler<HTMLDivElement>;
    onPaste?: React.ClipboardEventHandler<HTMLDivElement>;
    onPasteCapture?: React.ClipboardEventHandler<HTMLDivElement>;
    onCompositionEnd?: React.CompositionEventHandler<HTMLDivElement>;
    onCompositionEndCapture?: React.CompositionEventHandler<HTMLDivElement>;
    onCompositionStart?: React.CompositionEventHandler<HTMLDivElement>;
    onCompositionStartCapture?: React.CompositionEventHandler<HTMLDivElement>;
    onCompositionUpdate?: React.CompositionEventHandler<HTMLDivElement>;
    onCompositionUpdateCapture?: React.CompositionEventHandler<HTMLDivElement>;
    onFocus?: React.FocusEventHandler<HTMLDivElement>;
    onFocusCapture?: React.FocusEventHandler<HTMLDivElement>;
    onBlur?: React.FocusEventHandler<HTMLDivElement>;
    onBlurCapture?: React.FocusEventHandler<HTMLDivElement>;
    onChangeCapture?: React.FormEventHandler<HTMLDivElement>;
    onBeforeInput?: React.FormEventHandler<HTMLDivElement>;
    onBeforeInputCapture?: React.FormEventHandler<HTMLDivElement>;
    onInput?: React.FormEventHandler<HTMLDivElement>;
    onInputCapture?: React.FormEventHandler<HTMLDivElement>;
    onReset?: React.FormEventHandler<HTMLDivElement>;
    onResetCapture?: React.FormEventHandler<HTMLDivElement>;
    onSubmit?: React.FormEventHandler<HTMLDivElement>;
    onSubmitCapture?: React.FormEventHandler<HTMLDivElement>;
    onInvalid?: React.FormEventHandler<HTMLDivElement>;
    onInvalidCapture?: React.FormEventHandler<HTMLDivElement>;
    onLoad?: React.ReactEventHandler<HTMLDivElement>;
    onLoadCapture?: React.ReactEventHandler<HTMLDivElement>;
    onError?: React.ReactEventHandler<HTMLDivElement>;
    onErrorCapture?: React.ReactEventHandler<HTMLDivElement>;
    onKeyDown?: React.KeyboardEventHandler<HTMLDivElement>;
    onKeyDownCapture?: React.KeyboardEventHandler<HTMLDivElement>;
    onKeyPress?: React.KeyboardEventHandler<HTMLDivElement>;
    onKeyPressCapture?: React.KeyboardEventHandler<HTMLDivElement>;
    onKeyUp?: React.KeyboardEventHandler<HTMLDivElement>;
    onKeyUpCapture?: React.KeyboardEventHandler<HTMLDivElement>;
    onAbort?: React.ReactEventHandler<HTMLDivElement>;
    onAbortCapture?: React.ReactEventHandler<HTMLDivElement>;
    onCanPlay?: React.ReactEventHandler<HTMLDivElement>;
    onCanPlayCapture?: React.ReactEventHandler<HTMLDivElement>;
    onCanPlayThrough?: React.ReactEventHandler<HTMLDivElement>;
    onCanPlayThroughCapture?: React.ReactEventHandler<HTMLDivElement>;
    onDurationChange?: React.ReactEventHandler<HTMLDivElement>;
    onDurationChangeCapture?: React.ReactEventHandler<HTMLDivElement>;
    onEmptied?: React.ReactEventHandler<HTMLDivElement>;
    onEmptiedCapture?: React.ReactEventHandler<HTMLDivElement>;
    onEncrypted?: React.ReactEventHandler<HTMLDivElement>;
    onEncryptedCapture?: React.ReactEventHandler<HTMLDivElement>;
    onEnded?: React.ReactEventHandler<HTMLDivElement>;
    onEndedCapture?: React.ReactEventHandler<HTMLDivElement>;
    onLoadedData?: React.ReactEventHandler<HTMLDivElement>;
    onLoadedDataCapture?: React.ReactEventHandler<HTMLDivElement>;
    onLoadedMetadata?: React.ReactEventHandler<HTMLDivElement>;
    onLoadedMetadataCapture?: React.ReactEventHandler<HTMLDivElement>;
    onLoadStart?: React.ReactEventHandler<HTMLDivElement>;
    onLoadStartCapture?: React.ReactEventHandler<HTMLDivElement>;
    onPause?: React.ReactEventHandler<HTMLDivElement>;
    onPauseCapture?: React.ReactEventHandler<HTMLDivElement>;
    onPlay?: React.ReactEventHandler<HTMLDivElement>;
    onPlayCapture?: React.ReactEventHandler<HTMLDivElement>;
    onPlaying?: React.ReactEventHandler<HTMLDivElement>;
    onPlayingCapture?: React.ReactEventHandler<HTMLDivElement>;
    onProgress?: React.ReactEventHandler<HTMLDivElement>;
    onProgressCapture?: React.ReactEventHandler<HTMLDivElement>;
    onRateChange?: React.ReactEventHandler<HTMLDivElement>;
    onRateChangeCapture?: React.ReactEventHandler<HTMLDivElement>;
    onResize?: (size: import("jimu-ui").Size, position?: import("react-draggable").ControlPosition) => void;
    onResizeCapture?: React.ReactEventHandler<HTMLDivElement>;
    onSeeked?: React.ReactEventHandler<HTMLDivElement>;
    onSeekedCapture?: React.ReactEventHandler<HTMLDivElement>;
    onSeeking?: React.ReactEventHandler<HTMLDivElement>;
    onSeekingCapture?: React.ReactEventHandler<HTMLDivElement>;
    onStalled?: React.ReactEventHandler<HTMLDivElement>;
    onStalledCapture?: React.ReactEventHandler<HTMLDivElement>;
    onSuspend?: React.ReactEventHandler<HTMLDivElement>;
    onSuspendCapture?: React.ReactEventHandler<HTMLDivElement>;
    onTimeUpdate?: React.ReactEventHandler<HTMLDivElement>;
    onTimeUpdateCapture?: React.ReactEventHandler<HTMLDivElement>;
    onVolumeChange?: React.ReactEventHandler<HTMLDivElement>;
    onVolumeChangeCapture?: React.ReactEventHandler<HTMLDivElement>;
    onWaiting?: React.ReactEventHandler<HTMLDivElement>;
    onWaitingCapture?: React.ReactEventHandler<HTMLDivElement>;
    onAuxClick?: React.MouseEventHandler<HTMLDivElement>;
    onAuxClickCapture?: React.MouseEventHandler<HTMLDivElement>;
    onClickCapture?: React.MouseEventHandler<HTMLDivElement>;
    onContextMenu?: React.MouseEventHandler<HTMLDivElement>;
    onContextMenuCapture?: React.MouseEventHandler<HTMLDivElement>;
    onDoubleClick?: React.MouseEventHandler<HTMLDivElement>;
    onDoubleClickCapture?: React.MouseEventHandler<HTMLDivElement>;
    onDragCapture?: React.DragEventHandler<HTMLDivElement>;
    onDragEnd?: React.DragEventHandler<HTMLDivElement>;
    onDragEndCapture?: React.DragEventHandler<HTMLDivElement>;
    onDragEnter?: React.DragEventHandler<HTMLDivElement>;
    onDragEnterCapture?: React.DragEventHandler<HTMLDivElement>;
    onDragExit?: React.DragEventHandler<HTMLDivElement>;
    onDragExitCapture?: React.DragEventHandler<HTMLDivElement>;
    onDragLeave?: React.DragEventHandler<HTMLDivElement>;
    onDragLeaveCapture?: React.DragEventHandler<HTMLDivElement>;
    onDragOver?: React.DragEventHandler<HTMLDivElement>;
    onDragOverCapture?: React.DragEventHandler<HTMLDivElement>;
    onDragStart?: import("react-draggable").DraggableEventHandler;
    onDragStartCapture?: React.DragEventHandler<HTMLDivElement>;
    onDrop?: React.DragEventHandler<HTMLDivElement>;
    onDropCapture?: React.DragEventHandler<HTMLDivElement>;
    onMouseDownCapture?: React.MouseEventHandler<HTMLDivElement>;
    onMouseEnter?: React.MouseEventHandler<HTMLDivElement>;
    onMouseLeave?: React.MouseEventHandler<HTMLDivElement>;
    onMouseMove?: React.MouseEventHandler<HTMLDivElement>;
    onMouseMoveCapture?: React.MouseEventHandler<HTMLDivElement>;
    onMouseOut?: React.MouseEventHandler<HTMLDivElement>;
    onMouseOutCapture?: React.MouseEventHandler<HTMLDivElement>;
    onMouseOver?: React.MouseEventHandler<HTMLDivElement>;
    onMouseOverCapture?: React.MouseEventHandler<HTMLDivElement>;
    onMouseUp?: React.MouseEventHandler<HTMLDivElement>;
    onMouseUpCapture?: React.MouseEventHandler<HTMLDivElement>;
    onSelect?: React.ReactEventHandler<HTMLDivElement>;
    onSelectCapture?: React.ReactEventHandler<HTMLDivElement>;
    onTouchCancel?: React.TouchEventHandler<HTMLDivElement>;
    onTouchCancelCapture?: React.TouchEventHandler<HTMLDivElement>;
    onTouchEnd?: React.TouchEventHandler<HTMLDivElement>;
    onTouchEndCapture?: React.TouchEventHandler<HTMLDivElement>;
    onTouchMove?: React.TouchEventHandler<HTMLDivElement>;
    onTouchMoveCapture?: React.TouchEventHandler<HTMLDivElement>;
    onTouchStart?: React.TouchEventHandler<HTMLDivElement>;
    onTouchStartCapture?: React.TouchEventHandler<HTMLDivElement>;
    onPointerDown?: React.PointerEventHandler<HTMLDivElement>;
    onPointerDownCapture?: React.PointerEventHandler<HTMLDivElement>;
    onPointerMove?: React.PointerEventHandler<HTMLDivElement>;
    onPointerMoveCapture?: React.PointerEventHandler<HTMLDivElement>;
    onPointerUp?: React.PointerEventHandler<HTMLDivElement>;
    onPointerUpCapture?: React.PointerEventHandler<HTMLDivElement>;
    onPointerCancel?: React.PointerEventHandler<HTMLDivElement>;
    onPointerCancelCapture?: React.PointerEventHandler<HTMLDivElement>;
    onPointerEnter?: React.PointerEventHandler<HTMLDivElement>;
    onPointerEnterCapture?: React.PointerEventHandler<HTMLDivElement>;
    onPointerLeave?: React.PointerEventHandler<HTMLDivElement>;
    onPointerLeaveCapture?: React.PointerEventHandler<HTMLDivElement>;
    onPointerOver?: React.PointerEventHandler<HTMLDivElement>;
    onPointerOverCapture?: React.PointerEventHandler<HTMLDivElement>;
    onPointerOut?: React.PointerEventHandler<HTMLDivElement>;
    onPointerOutCapture?: React.PointerEventHandler<HTMLDivElement>;
    onGotPointerCapture?: React.PointerEventHandler<HTMLDivElement>;
    onGotPointerCaptureCapture?: React.PointerEventHandler<HTMLDivElement>;
    onLostPointerCapture?: React.PointerEventHandler<HTMLDivElement>;
    onLostPointerCaptureCapture?: React.PointerEventHandler<HTMLDivElement>;
    onScroll?: React.UIEventHandler<HTMLDivElement>;
    onScrollCapture?: React.UIEventHandler<HTMLDivElement>;
    onWheel?: React.WheelEventHandler<HTMLDivElement>;
    onWheelCapture?: React.WheelEventHandler<HTMLDivElement>;
    onAnimationStart?: React.AnimationEventHandler<HTMLDivElement>;
    onAnimationStartCapture?: React.AnimationEventHandler<HTMLDivElement>;
    onAnimationEnd?: React.AnimationEventHandler<HTMLDivElement>;
    onAnimationEndCapture?: React.AnimationEventHandler<HTMLDivElement>;
    onAnimationIteration?: React.AnimationEventHandler<HTMLDivElement>;
    onAnimationIterationCapture?: React.AnimationEventHandler<HTMLDivElement>;
    onTransitionEnd?: React.TransitionEventHandler<HTMLDivElement>;
    onTransitionEndCapture?: React.TransitionEventHandler<HTMLDivElement>;
    version?: number;
    key?: React.Key;
    manifest?: string;
    toggle?: (evt?: React.MouseEvent<any, MouseEvent> | React.TouchEvent<any>, type?: "appMode" | "clickOutside" | "pageOrSizeMode") => any;
    modifiers?: import("jimu-ui").Modifiers;
    strategy?: import("jimu-ui").PositioningStrategy;
    showArrow?: boolean;
    trapFocus?: boolean;
    forceLatestFocusElements?: boolean;
    avoidNestedToggle?: boolean;
    delayToggle?: number;
    referenceHiddenVisibility?: boolean;
    reference: import("jimu-ui").TargetType;
    onFirstUpdate?: (state: import("@popperjs/core").State) => void;
    placement?: import("jimu-ui").Placement;
    headerTitle?: React.ReactNode;
    headerClassName?: string;
    showHeaderClose?: boolean;
    showHeaderCollapse?: boolean;
    onHeaderClose?: (e?: React.MouseEvent<HTMLDivElement, MouseEvent>) => void;
    minSize?: import("jimu-ui").Size;
    defaultSize?: import("jimu-ui").Size;
    defaultPosition?: import("react-draggable").ControlPosition;
    positionOffset?: import("react-draggable").PositionOffsetControlPosition;
    disableResize?: boolean;
    disableDraggable?: boolean;
    resizeGrid?: [number, number];
    onResizeStart?: (size: import("jimu-ui").Size, position?: import("react-draggable").ControlPosition) => void;
    onResizeStop?: (size: import("jimu-ui").Size, position?: import("react-draggable").ControlPosition) => void;
    resizeHandles?: import("jimu-ui").ResizeHandle[];
    dragBounds?: string | false | import("react-draggable").DraggableBounds;
    dragGrid?: [number, number];
    dragOffsetParent?: HTMLElement;
    onDragStop?: import("react-draggable").DraggableEventHandler;
    dragScale?: number;
    onLeave?: () => void;
    activateOnlyForHeader?: boolean;
    onHeaderClick?: (e?: React.MouseEvent<HTMLDivElement, MouseEvent>) => void;
    disablePortal?: boolean;
    disableActivateOverlay?: boolean;
    disableOverlayManager?: boolean;
    floating?: boolean;
    arrowStyle?: import("jimu-theme").ArrowStyle;
    flipPlacement?: boolean;
    keepMount?: boolean;
    popperNodeRef?: React.Ref<HTMLDivElement>;
    listenContextPopperVersion?: boolean;
    context?: React.Context<ReactRedux.ReactReduxContextValue<any, import("redux").AnyAction>>;
    store?: import("redux").Store<any, import("redux").AnyAction>;
}>;
export default _default;
